/**
 * @file ./out/parser/bool_literal.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * bool_literal (
 *     TOK_TRUE |
 *     TOK_FALSE
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     terminal rule element: TOK_TRUE
 *     terminal rule element: TOK_FALSE
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_bool_literal_t* parse_bool_literal(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_bool_literal_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1100:1
            case 1100:
                // terminal rule element: TOK_TRUE
                // terminal rule element: TOK_FALSE
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_bool_literal_t*)create_ast_node(AST_BOOL_LITERAL);

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
