/**
 * @file ./out/parser/compound_reference.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * compound_reference (
 *     compound_reference_element ( TOK_DOT compound_reference_element ) *
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: compound_reference_element
 *   begin zero_or_more_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_DOT
 *       non-terminal rule element: compound_reference_element
 *     end grouping_function (1200)
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
ast_compound_reference_t* parse_compound_reference(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_compound_reference_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_compound_reference_element_t* compound_reference_element = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_compound_reference_element_t* compound_reference_element = NULL;


    while(!finished) {
        switch(state) {

            // begin grouping_function rule at state 1200:2
            case 1200:
                // terminal rule element: TOK_DOT
                // non-terminal rule element: compound_reference_element
                break;
            // end grouping_function rule at state 1200

            // begin zero_or_more_function rule at state 1100:1
            case 1100:
                break;
            // end zero_or_more_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                // non-terminal rule element: compound_reference_element
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_compound_reference_t*)create_ast_node(AST_COMPOUND_REFERENCE);
                // retv->compound_reference_element = compound_reference_element;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->compound_reference_element = compound_reference_element;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
