/**
 * @file ./out/parser/data_definition.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * data_definition (
 *     TOK_CONST ? data_declaration ( TOK_EQUAL initializer ) ?
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin zero_or_one_function (1100)
 *     terminal rule element: TOK_CONST
 *   end zero_or_one_function (1100)
 *   non-terminal rule element: data_declaration
 *   begin zero_or_one_function (1200)
 *     begin grouping_function (1300)
 *       terminal rule element: TOK_EQUAL
 *       non-terminal rule element: initializer
 *     end grouping_function (1300)
 *   end zero_or_one_function (1200)
 * end grouping_function (1000)
 *
 */
ast_data_definition_t* parse_data_definition(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_data_definition_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_data_declaration_t* data_declaration = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_initializer_t* initializer = NULL;


    while(!finished) {
        switch(state) {

            // begin zero_or_one_function rule at state 1100:1
            case 1100:
                // terminal rule element: TOK_CONST
                break;
            // end zero_or_one_function rule at state 1100

            // begin grouping_function rule at state 1300:2
            case 1300:
                // terminal rule element: TOK_EQUAL
                // non-terminal rule element: initializer
                break;
            // end grouping_function rule at state 1300

            // begin zero_or_one_function rule at state 1200:1
            case 1200:
                break;
            // end zero_or_one_function rule at state 1200

            // begin grouping_function rule at state 1000:0
            case 1000:
                // non-terminal rule element: data_declaration
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_data_definition_t*)create_ast_node(AST_DATA_DEFINITION);
                // retv->data_declaration = data_declaration;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->initializer = initializer;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
