/**
 * @file ./out/parser/dss_initializer_item.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * dss_initializer_item (
 *     TOK_STRING_LITERAL TOK_COLON expression
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_STRING_LITERAL
 *   terminal rule element: TOK_COLON
 *   non-terminal rule element: expression
 * end grouping_function (1000)
 *
 */
ast_dss_initializer_item_t* parse_dss_initializer_item(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_dss_initializer_item_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* STRING_LITERAL = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_expression_t* expression = NULL;


    while(!finished) {
        switch(state) {

            // begin grouping_function rule at state 1000:0
            case 1000:
                // terminal rule element: TOK_STRING_LITERAL
                // terminal rule element: TOK_COLON
                // non-terminal rule element: expression
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_dss_initializer_item_t*)create_ast_node(AST_DSS_INITIALIZER_ITEM);
                // retv->STRING_LITERAL = STRING_LITERAL;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->expression = expression;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
