/**
 * @file ./out/parser/final_else_clause.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * final_else_clause (
 *     TOK_ELSE ( TOK_OPAREN TOK_CPAREN ) ? function_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_ELSE
 *   begin zero_or_one_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_OPAREN
 *       terminal rule element: TOK_CPAREN
 *     end grouping_function (1200)
 *   end zero_or_one_function (1100)
 *   non-terminal rule element: function_body
 * end grouping_function (1000)
 *
 */
ast_final_else_clause_t* parse_final_else_clause(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_final_else_clause_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* TERMINAL_OPER = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_function_body_t* function_body = NULL;


    while(!finished) {
        switch(state) {

            // begin grouping_function rule at state 1200:2
            case 1200:
                // terminal rule element: TOK_OPAREN
                // terminal rule element: TOK_CPAREN
                break;
            // end grouping_function rule at state 1200

            // begin zero_or_one_function rule at state 1100:1
            case 1100:
                break;
            // end zero_or_one_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                // terminal rule element: TOK_ELSE
                // non-terminal rule element: function_body
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_final_else_clause_t*)create_ast_node(AST_FINAL_ELSE_CLAUSE);
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->function_body = function_body;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
