/**
 * @file ./out/parser/for_clause.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * for_clause (
 *     TOK_FOR ( TOK_OPAREN ( literal_type_name ? TOK_IDENTIFIER TOK_IN ) ? expression TOK_CPAREN ) ? loop_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_FOR
 *   begin zero_or_one_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_OPAREN
 *       begin zero_or_one_function (1300)
 *         begin grouping_function (1400)
 *           begin zero_or_one_function (1500)
 *             non-terminal rule element: literal_type_name
 *           end zero_or_one_function (1500)
 *           terminal rule element: TOK_IDENTIFIER
 *           terminal rule element: TOK_IN
 *         end grouping_function (1400)
 *       end zero_or_one_function (1300)
 *       non-terminal rule element: expression
 *       terminal rule element: TOK_CPAREN
 *     end grouping_function (1200)
 *   end zero_or_one_function (1100)
 *   non-terminal rule element: loop_body
 * end grouping_function (1000)
 *
 */
ast_for_clause_t* parse_for_clause(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_for_clause_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* TERMINAL_OPER = NULL;
    // ast_literal_type_name_t* literal_type_name = NULL;
    // token_t* IDENTIFIER = NULL;
    // ast_expression_t* expression = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_loop_body_t* loop_body = NULL;


    while(!finished) {
        switch(state) {

            // begin zero_or_one_function rule at state 1500:5
            case 1500:
                // non-terminal rule element: literal_type_name
                break;
            // end zero_or_one_function rule at state 1500

            // begin grouping_function rule at state 1400:4
            case 1400:
                // terminal rule element: TOK_IDENTIFIER
                // terminal rule element: TOK_IN
                break;
            // end grouping_function rule at state 1400

            // begin zero_or_one_function rule at state 1300:3
            case 1300:
                break;
            // end zero_or_one_function rule at state 1300

            // begin grouping_function rule at state 1200:2
            case 1200:
                // terminal rule element: TOK_OPAREN
                // non-terminal rule element: expression
                // terminal rule element: TOK_CPAREN
                break;
            // end grouping_function rule at state 1200

            // begin zero_or_one_function rule at state 1100:1
            case 1100:
                break;
            // end zero_or_one_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                // terminal rule element: TOK_FOR
                // non-terminal rule element: loop_body
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_for_clause_t*)create_ast_node(AST_FOR_CLAUSE);
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->literal_type_name = literal_type_name;
                // retv->IDENTIFIER = IDENTIFIER;
                // retv->expression = expression;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->loop_body = loop_body;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
