/**
 * @file ./out/parser/formatted_string.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * formatted_string (
 *     TOK_STRING_LITERAL ( TOK_OPAREN dss_initializer ? TOK_CPAREN ) ?
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_STRING_LITERAL
 *   begin zero_or_one_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_OPAREN
 *       begin zero_or_one_function (1300)
 *         non-terminal rule element: dss_initializer
 *       end zero_or_one_function (1300)
 *       terminal rule element: TOK_CPAREN
 *     end grouping_function (1200)
 *   end zero_or_one_function (1100)
 * end grouping_function (1000)
 *
 */
ast_formatted_string_t* parse_formatted_string(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_formatted_string_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* STRING_LITERAL = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_dss_initializer_t* dss_initializer = NULL;
    // token_t* TERMINAL_OPER = NULL;


    while(!finished) {
        switch(state) {

            // begin zero_or_one_function rule at state 1300:3
            case 1300:
                // non-terminal rule element: dss_initializer
                break;
            // end zero_or_one_function rule at state 1300

            // begin grouping_function rule at state 1200:2
            case 1200:
                // terminal rule element: TOK_OPAREN
                // terminal rule element: TOK_CPAREN
                break;
            // end grouping_function rule at state 1200

            // begin zero_or_one_function rule at state 1100:1
            case 1100:
                break;
            // end zero_or_one_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                // terminal rule element: TOK_STRING_LITERAL
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_formatted_string_t*)create_ast_node(AST_FORMATTED_STRING);
                // retv->STRING_LITERAL = STRING_LITERAL;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->dss_initializer = dss_initializer;
                // retv->TERMINAL_OPER = TERMINAL_OPER;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
