/**
 * @file ./out/parser/function_reference.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * function_reference (
 *     TOK_IDENTIFIER TOK_OPAREN expression_list TOK_CPAREN
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_IDENTIFIER
 *   terminal rule element: TOK_OPAREN
 *   non-terminal rule element: expression_list
 *   terminal rule element: TOK_CPAREN
 * end grouping_function (1000)
 *
 */
ast_function_reference_t* parse_function_reference(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_function_reference_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* IDENTIFIER = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_expression_list_t* expression_list = NULL;
    // token_t* TERMINAL_OPER = NULL;


    while(!finished) {
        switch(state) {

            // begin grouping_function rule at state 1000:0
            case 1000:
                // terminal rule element: TOK_IDENTIFIER
                // terminal rule element: TOK_OPAREN
                // non-terminal rule element: expression_list
                // terminal rule element: TOK_CPAREN
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_function_reference_t*)create_ast_node(AST_FUNCTION_REFERENCE);
                // retv->IDENTIFIER = IDENTIFIER;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->expression_list = expression_list;
                // retv->TERMINAL_OPER = TERMINAL_OPER;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
