/**
 * @file ./out/parser/function_body_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * function_body_element (
 *     assignment |
 *     compound_reference |
 *     data_definition |
 *     struct_definition |
 *     if_clause |
 *     while_clause |
 *     do_clause |
 *     for_clause |
 *     return_statement |
 *     exit_statement |
 *     TOK_INLINE
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         begin or_function (1400)
 *           begin or_function (1500)
 *             begin or_function (1600)
 *               begin or_function (1700)
 *                 begin or_function (1800)
 *                   begin or_function (1900)
 *                     begin or_function (2000)
 *                       non-terminal rule element: assignment
 *                       non-terminal rule element: compound_reference
 *                     end or_function (2000)
 *                     non-terminal rule element: data_definition
 *                   end or_function (1900)
 *                   non-terminal rule element: struct_definition
 *                 end or_function (1800)
 *                 non-terminal rule element: if_clause
 *               end or_function (1700)
 *               non-terminal rule element: while_clause
 *             end or_function (1600)
 *             non-terminal rule element: do_clause
 *           end or_function (1500)
 *           non-terminal rule element: for_clause
 *         end or_function (1400)
 *         non-terminal rule element: return_statement
 *       end or_function (1300)
 *       non-terminal rule element: exit_statement
 *     end or_function (1200)
 *     terminal rule element: TOK_INLINE
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_function_body_element_t* parse_function_body_element(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_function_body_element_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_assignment_t* assignment = NULL;
    // ast_compound_reference_t* compound_reference = NULL;
    // ast_data_definition_t* data_definition = NULL;
    // ast_struct_definition_t* struct_definition = NULL;
    // ast_if_clause_t* if_clause = NULL;
    // ast_while_clause_t* while_clause = NULL;
    // ast_do_clause_t* do_clause = NULL;
    // ast_for_clause_t* for_clause = NULL;
    // ast_return_statement_t* return_statement = NULL;
    // ast_exit_statement_t* exit_statement = NULL;
    // token_t* INLINE = NULL;


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 2000:10
            case 2000:
                // non-terminal rule element: assignment
                // non-terminal rule element: compound_reference
                break;
            // end or_function rule at state 2000

            // begin or_function rule at state 1900:9
            case 1900:
                // non-terminal rule element: data_definition
                break;
            // end or_function rule at state 1900

            // begin or_function rule at state 1800:8
            case 1800:
                // non-terminal rule element: struct_definition
                break;
            // end or_function rule at state 1800

            // begin or_function rule at state 1700:7
            case 1700:
                // non-terminal rule element: if_clause
                break;
            // end or_function rule at state 1700

            // begin or_function rule at state 1600:6
            case 1600:
                // non-terminal rule element: while_clause
                break;
            // end or_function rule at state 1600

            // begin or_function rule at state 1500:5
            case 1500:
                // non-terminal rule element: do_clause
                break;
            // end or_function rule at state 1500

            // begin or_function rule at state 1400:4
            case 1400:
                // non-terminal rule element: for_clause
                break;
            // end or_function rule at state 1400

            // begin or_function rule at state 1300:3
            case 1300:
                // non-terminal rule element: return_statement
                break;
            // end or_function rule at state 1300

            // begin or_function rule at state 1200:2
            case 1200:
                // non-terminal rule element: exit_statement
                break;
            // end or_function rule at state 1200

            // begin or_function rule at state 1100:1
            case 1100:
                // terminal rule element: TOK_INLINE
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_function_body_element_t*)create_ast_node(AST_FUNCTION_BODY_ELEMENT);
                // retv->assignment = assignment;
                // retv->compound_reference = compound_reference;
                // retv->data_definition = data_definition;
                // retv->struct_definition = struct_definition;
                // retv->if_clause = if_clause;
                // retv->while_clause = while_clause;
                // retv->do_clause = do_clause;
                // retv->for_clause = for_clause;
                // retv->return_statement = return_statement;
                // retv->exit_statement = exit_statement;
                // retv->INLINE = INLINE;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
