/**
 * @file ./out/parser/function_body_prelist.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * function_body_prelist (
 *     function_body_element |
 *     function_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     non-terminal rule element: function_body_element
 *     non-terminal rule element: function_body
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_function_body_prelist_t* parse_function_body_prelist(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_function_body_prelist_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_function_body_element_t* function_body_element = NULL;
    // ast_function_body_t* function_body = NULL;


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1100:1
            case 1100:
                // non-terminal rule element: function_body_element
                // non-terminal rule element: function_body
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_function_body_prelist_t*)create_ast_node(AST_FUNCTION_BODY_PRELIST);
                // retv->function_body_element = function_body_element;
                // retv->function_body = function_body;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
