/**
 * @file ./out/parser/initializer.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * initializer (
 *     expression |
 *     list_init |
 *     dict_init |
 *     struct_init
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         non-terminal rule element: expression
 *         non-terminal rule element: list_init
 *       end or_function (1300)
 *       non-terminal rule element: dict_init
 *     end or_function (1200)
 *     non-terminal rule element: struct_init
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_initializer_t* parse_initializer(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_initializer_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_expression_t* expression = NULL;
    // ast_list_init_t* list_init = NULL;
    // ast_dict_init_t* dict_init = NULL;
    // ast_struct_init_t* struct_init = NULL;


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1300:3
            case 1300:
                // non-terminal rule element: expression
                // non-terminal rule element: list_init
                break;
            // end or_function rule at state 1300

            // begin or_function rule at state 1200:2
            case 1200:
                // non-terminal rule element: dict_init
                break;
            // end or_function rule at state 1200

            // begin or_function rule at state 1100:1
            case 1100:
                // non-terminal rule element: struct_init
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_initializer_t*)create_ast_node(AST_INITIALIZER);
                // retv->expression = expression;
                // retv->list_init = list_init;
                // retv->dict_init = dict_init;
                // retv->struct_init = struct_init;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
