/**
 * @file ./out/parser/literal_type_name.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * literal_type_name (
 *     TOK_INT |
 *     TOK_FLOAT |
 *     TOK_STRING |
 *     TOK_LIST |
 *     TOK_DICT |
 *     TOK_BOOL
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         begin or_function (1400)
 *           begin or_function (1500)
 *             terminal rule element: TOK_INT
 *             terminal rule element: TOK_FLOAT
 *           end or_function (1500)
 *           terminal rule element: TOK_STRING
 *         end or_function (1400)
 *         terminal rule element: TOK_LIST
 *       end or_function (1300)
 *       terminal rule element: TOK_DICT
 *     end or_function (1200)
 *     terminal rule element: TOK_BOOL
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_literal_type_name_t* parse_literal_type_name(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_literal_type_name_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1500:5
            case 1500:
                // terminal rule element: TOK_INT
                // terminal rule element: TOK_FLOAT
                break;
            // end or_function rule at state 1500

            // begin or_function rule at state 1400:4
            case 1400:
                // terminal rule element: TOK_STRING
                break;
            // end or_function rule at state 1400

            // begin or_function rule at state 1300:3
            case 1300:
                // terminal rule element: TOK_LIST
                break;
            // end or_function rule at state 1300

            // begin or_function rule at state 1200:2
            case 1200:
                // terminal rule element: TOK_DICT
                break;
            // end or_function rule at state 1200

            // begin or_function rule at state 1100:1
            case 1100:
                // terminal rule element: TOK_BOOL
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_literal_type_name_t*)create_ast_node(AST_LITERAL_TYPE_NAME);

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
