/**
 * @file ./out/parser/loop_body_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * loop_body_element (
 *     function_body_element |
 *     TOK_CONTINUE |
 *     TOK_BREAK
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       non-terminal rule element: function_body_element
 *       terminal rule element: TOK_CONTINUE
 *     end or_function (1200)
 *     terminal rule element: TOK_BREAK
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_loop_body_element_t* parse_loop_body_element(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_loop_body_element_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_function_body_element_t* function_body_element = NULL;
    // token_t* CONTINUE = NULL;
    // token_t* BREAK = NULL;


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1200:2
            case 1200:
                // non-terminal rule element: function_body_element
                // terminal rule element: TOK_CONTINUE
                break;
            // end or_function rule at state 1200

            // begin or_function rule at state 1100:1
            case 1100:
                // terminal rule element: TOK_BREAK
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_loop_body_element_t*)create_ast_node(AST_LOOP_BODY_ELEMENT);
                // retv->function_body_element = function_body_element;
                // retv->CONTINUE = CONTINUE;
                // retv->BREAK = BREAK;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
