/**
 * @file ./out/parser/primary_expression.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * primary_expression (
 *     TOK_INT_LITERAL |
 *     TOK_FLOAT_LITERAL |
 *     formatted_string |
 *     bool_literal |
 *     ( TOK_OPAREN expression TOK_CPAREN ) |
 *     compound_reference
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         begin or_function (1400)
 *           begin or_function (1500)
 *             terminal rule element: TOK_INT_LITERAL
 *             terminal rule element: TOK_FLOAT_LITERAL
 *           end or_function (1500)
 *           non-terminal rule element: formatted_string
 *         end or_function (1400)
 *         non-terminal rule element: bool_literal
 *       end or_function (1300)
 *       begin grouping_function (1600)
 *         terminal rule element: TOK_OPAREN
 *         non-terminal rule element: expression
 *         terminal rule element: TOK_CPAREN
 *       end grouping_function (1600)
 *     end or_function (1200)
 *     non-terminal rule element: compound_reference
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
ast_primary_expression_t* parse_primary_expression(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_primary_expression_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* INT_LITERAL = NULL;
    // token_t* FLOAT_LITERAL = NULL;
    // ast_formatted_string_t* formatted_string = NULL;
    // ast_bool_literal_t* bool_literal = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_expression_t* expression = NULL;
    // token_t* TERMINAL_OPER = NULL;
    // ast_compound_reference_t* compound_reference = NULL;


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1500:5
            case 1500:
                // terminal rule element: TOK_INT_LITERAL
                // terminal rule element: TOK_FLOAT_LITERAL
                break;
            // end or_function rule at state 1500

            // begin or_function rule at state 1400:4
            case 1400:
                // non-terminal rule element: formatted_string
                break;
            // end or_function rule at state 1400

            // begin or_function rule at state 1300:3
            case 1300:
                // non-terminal rule element: bool_literal
                break;
            // end or_function rule at state 1300

            // begin grouping_function rule at state 1600:3
            case 1600:
                // terminal rule element: TOK_OPAREN
                // non-terminal rule element: expression
                // terminal rule element: TOK_CPAREN
                break;
            // end grouping_function rule at state 1600

            // begin or_function rule at state 1200:2
            case 1200:
                break;
            // end or_function rule at state 1200

            // begin or_function rule at state 1100:1
            case 1100:
                // non-terminal rule element: compound_reference
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_primary_expression_t*)create_ast_node(AST_PRIMARY_EXPRESSION);
                // retv->INT_LITERAL = INT_LITERAL;
                // retv->FLOAT_LITERAL = FLOAT_LITERAL;
                // retv->formatted_string = formatted_string;
                // retv->bool_literal = bool_literal;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->expression = expression;
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->compound_reference = compound_reference;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
