/**
 * @file ./out/parser/struct_init.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * struct_init (
 *     TOK_OCBRACE dss_initializer TOK_CCBRACE
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_OCBRACE
 *   non-terminal rule element: dss_initializer
 *   terminal rule element: TOK_CCBRACE
 * end grouping_function (1000)
 *
 */
ast_struct_init_t* parse_struct_init(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_struct_init_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // token_t* TERMINAL_OPER = NULL;
    // ast_dss_initializer_t* dss_initializer = NULL;
    // token_t* TERMINAL_OPER = NULL;


    while(!finished) {
        switch(state) {

            // begin grouping_function rule at state 1000:0
            case 1000:
                // terminal rule element: TOK_OCBRACE
                // non-terminal rule element: dss_initializer
                // terminal rule element: TOK_CCBRACE
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_struct_init_t*)create_ast_node(AST_STRUCT_INIT);
                // retv->TERMINAL_OPER = TERMINAL_OPER;
                // retv->dss_initializer = dss_initializer;
                // retv->TERMINAL_OPER = TERMINAL_OPER;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
