/**
 * @file ./out/parser/translation_unit_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * translation_unit_element (
 *     import_statement |
 *     data_definition |
 *     function_definition |
 *     struct_definition start_block
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         non-terminal rule element: import_statement
 *         non-terminal rule element: data_definition
 *       end or_function (1300)
 *       non-terminal rule element: function_definition
 *     end or_function (1200)
 *     non-terminal rule element: struct_definition
 *   end or_function (1100)
 *   non-terminal rule element: start_block
 * end grouping_function (1000)
 *
 */
ast_translation_unit_element_t* parse_translation_unit_element(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_translation_unit_element_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_import_statement_t* import_statement = NULL;
    // ast_data_definition_t* data_definition = NULL;
    // ast_function_definition_t* function_definition = NULL;
    // ast_struct_definition_t* struct_definition = NULL;
    // ast_start_block_t* start_block = NULL;


    while(!finished) {
        switch(state) {

            // begin or_function rule at state 1300:3
            case 1300:
                // non-terminal rule element: import_statement
                // non-terminal rule element: data_definition
                break;
            // end or_function rule at state 1300

            // begin or_function rule at state 1200:2
            case 1200:
                // non-terminal rule element: function_definition
                break;
            // end or_function rule at state 1200

            // begin or_function rule at state 1100:1
            case 1100:
                // non-terminal rule element: struct_definition
                break;
            // end or_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                // non-terminal rule element: start_block
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_translation_unit_element_t*)create_ast_node(AST_TRANSLATION_UNIT_ELEMENT);
                // retv->import_statement = import_statement;
                // retv->data_definition = data_definition;
                // retv->function_definition = function_definition;
                // retv->struct_definition = struct_definition;
                // retv->start_block = start_block;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
