/**
 * @file ./out/parser/translation_unit.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "errors.h"
#include "parser_protos.h"

/*
 * translation_unit (
 *     translation_unit_element *
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin zero_or_more_function (1100)
 *     non-terminal rule element: translation_unit_element
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
ast_translation_unit_t* parse_translation_unit(parser_state_t* pstate) {

    ENTER;
    ASSERT(pstate != NULL, "null pstate is not allowed");
    ast_translation_unit_t* retv = NULL;
    int state = 1000;
    bool finished = false;
    void* post = mark_token_queue();

    // ast_translation_unit_element_t* translation_unit_element = NULL;


    while(!finished) {
        switch(state) {

            // begin zero_or_more_function rule at state 1100:1
            case 1100:
                // non-terminal rule element: translation_unit_element
                break;
            // end zero_or_more_function rule at state 1100

            // begin grouping_function rule at state 1000:0
            case 1000:
                break;
                // end grouping_function rule at state 1000


            case STATE_MATCH:
                TRACE_STATE;
                consume_token_queue();
                retv = (ast_translation_unit_t*)create_ast_node(AST_TRANSLATION_UNIT);
                // retv->translation_unit_element = translation_unit_element;

                break;
            case STATE_NO_MATCH:
                TRACE_STATE;
                restore_token_queue(post);
                finished = true;
                break;
            case STATE_ERROR:
                TRACE_STATE;
                restore_token_queue(post);
                recover_parser_error(pstate);
                finished = true;
                break;
            default:
                FATAL("unknown state: %d", state);
        }
    }

    RETURN(retv);
}
