/*
 *  Tokens that the lexer will return.
 */
#ifndef _PARSER_H_
#define _PARSER_H_

enum
{
    NOTHING_TOK = 300,
    TRUE_TOK,
    FALSE_TOK,
    INCLUDE_TOK,
    VAR_TOK,
    CLASS_TOK,
    METHOD_TOK,
    CREATE_TOK,
    DESTROY_TOK,
    PUBLIC_TOK,
    PRIVATE_TOK,
    PROTECTED_TOK,
    STATIC_TOK,
    CONST_TOK,
    DICT_TOK,
    ARRAY_TOK,
    BOOL_TOK,
    STRING_TOK,
    INT8_TOK,
    INT16_TOK,
    INT32_TOK,
    INT64_TOK,
    INT_TOK,
    FLOAT_TOK,
    UINT8_TOK,
    UINT16_TOK,
    UINT32_TOK,
    UINT64_TOK,
    UINT_TOK,
    IF_TOK,
    ELSEIF_TOK,
    ELSE_TOK,
    FOR_TOK,
    WHILE_TOK,
    DO_TOK,
    RAISE_TOK,
    EXCEPT_TOK,
    SWITCH_TOK,
    CASE_TOK,
    BREAK_TOK,
    CONTINUE_TOK,
    AND_TOK,
    OR_TOK,
    NOT_TOK,
    EQU_TOK,
    NEQU_TOK,
    LTEQU_TOK,
    GTEQU_TOK,
    LESS_TOK,
    MORE_TOK,
    SYMBOL_TOK,
    COMPLEX_TOK,
    QSTRG_TOK,
    SNUM_TOK,
    UNUM_TOK,
    FNUM_TOK,
    EOF_TOK,
    DUMMY,
} _token_t;

#endif /* !_PARSER_H_  */
