/**
 * @file ./out/scanner/file_io.h
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#ifndef _FILE_IO_H_
#define _FILE_IO_H_

#include "string_buffer.h"

void open_file(const char* name);
void close_file(void);
int get_char(void);
int get_line_no(void);
int get_col_no(void);
string_t* get_file_name(void);
void update_numbers(void);

#endif /* _FILE_IO_H_ */
