/**
 * @file ./out/ast/assignment.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the assignment data structure.
 *
 * assignment (
 *     compound_name TOK_EQUAL expression
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: compound_name
 *   terminal rule element: TOK_EQUAL
 *   non-terminal rule element: expression
 * end grouping_function (1000)
 *
 */
void traverse_assignment(ast_assignment_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_NODE(compound_name);
    TRAVERSE_NODE(expression);


    RETURN();
}

