/**
 * @file ./out/ast/ast.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "ast.h"
#include "ast_protos.h"
#include "alloc.h"
#include "cmdline.h"
#include "trace.h"

/*
 * public interface
 */
ast_node_t* create_ast_node(ast_type_t type) {

    ast_node_t* ptr = _ALLOC(get_node_size(type));
    ptr->type = type;

    return ptr;
}

void traverse_ast(ast_node_t* node) {

    if(in_cmd_list("trace", "ast"))
        push_trace_state(1);
    else
        push_trace_state(0);

    traverse_translation_unit((ast_translation_unit_t*)node);

    pop_trace_state();
}

const char* node_type_to_str(ast_type_t type) {

    return (type == AST_ASSIGNMENT)                  ? "assignment" :
            (type == AST_BOOL_LITERAL)               ? "bool_literal" :
            (type == AST_COMPOUND_NAME)              ? "compound_name" :
            (type == AST_COMPOUND_REFERENCE)         ? "compound_reference" :
            (type == AST_COMPOUND_REFERENCE_ELEMENT) ? "compound_reference_element" :
            (type == AST_DATA_DECLARATION)           ? "data_declaration" :
            (type == AST_DATA_DEFINITION)            ? "data_definition" :
            (type == AST_DICT_INIT)                  ? "dict_init" :
            (type == AST_DO_CLAUSE)                  ? "do_clause" :
            (type == AST_DSS_INITIALIZER)            ? "dss_initializer" :
            (type == AST_DSS_INITIALIZER_ITEM)       ? "dss_initializer_item" :
            (type == AST_ELSE_CLAUSE)                ? "else_clause" :
            (type == AST_EXIT_STATEMENT)             ? "exit_statement" :
            (type == AST_EXPRESSION)                 ? "expression" :
            (type == AST_EXPRESSION_LIST)            ? "expression_list" :
            (type == AST_FINAL_ELSE_CLAUSE)          ? "final_else_clause" :
            (type == AST_FOR_CLAUSE)                 ? "for_clause" :
            (type == AST_FORMATTED_STRING)           ? "formatted_string" :
            (type == AST_FUNCTION_BODY)              ? "function_body" :
            (type == AST_FUNCTION_BODY_ELEMENT)      ? "function_body_element" :
            (type == AST_FUNCTION_BODY_LIST)         ? "function_body_list" :
            (type == AST_FUNCTION_BODY_PRELIST)      ? "function_body_prelist" :
            (type == AST_FUNCTION_DEFINITION)        ? "function_definition" :
            (type == AST_FUNCTION_NAME)              ? "function_name" :
            (type == AST_FUNCTION_PARAMETERS)        ? "function_parameters" :
            (type == AST_FUNCTION_REFERENCE)         ? "function_reference" :
            (type == AST_IF_CLAUSE)                  ? "if_clause" :
            (type == AST_IMPORT_STATEMENT)           ? "import_statement" :
            (type == AST_INITIALIZER)                ? "initializer" :
            (type == AST_LIST_INIT)                  ? "list_init" :
            (type == AST_LIST_REFERENCE)             ? "list_reference" :
            (type == AST_LITERAL_TYPE_NAME)          ? "literal_type_name" :
            (type == AST_LOOP_BODY)                  ? "loop_body" :
            (type == AST_LOOP_BODY_ELEMENT)          ? "loop_body_element" :
            (type == AST_LOOP_BODY_LIST)             ? "loop_body_list" :
            (type == AST_LOOP_BODY_PRELIST)          ? "loop_body_prelist" :
            (type == AST_PRIMARY_EXPRESSION)         ? "primary_expression" :
            (type == AST_RETURN_STATEMENT)           ? "return_statement" :
            (type == AST_START_BLOCK)                ? "start_block" :
            (type == AST_STRUCT_DEFINITION)          ? "struct_definition" :
            (type == AST_STRUCT_INIT)                ? "struct_init" :
            (type == AST_TRANSLATION_UNIT)           ? "translation_unit" :
            (type == AST_TRANSLATION_UNIT_ELEMENT)   ? "translation_unit_element" :
            (type == AST_TYPE_NAME)                  ? "type_name" :
            (type == AST_WHILE_CLAUSE)               ? "while_clause" :
                                                       "UNKNOWN";
}

size_t get_node_size(ast_type_t type) {

    return (type == AST_ASSIGNMENT)                  ? sizeof(ast_assignment_t) :
            (type == AST_BOOL_LITERAL)               ? sizeof(ast_bool_literal_t) :
            (type == AST_COMPOUND_NAME)              ? sizeof(ast_compound_name_t) :
            (type == AST_COMPOUND_REFERENCE)         ? sizeof(ast_compound_reference_t) :
            (type == AST_COMPOUND_REFERENCE_ELEMENT) ? sizeof(ast_compound_reference_element_t) :
            (type == AST_DATA_DECLARATION)           ? sizeof(ast_data_declaration_t) :
            (type == AST_DATA_DEFINITION)            ? sizeof(ast_data_definition_t) :
            (type == AST_DICT_INIT)                  ? sizeof(ast_dict_init_t) :
            (type == AST_DO_CLAUSE)                  ? sizeof(ast_do_clause_t) :
            (type == AST_DSS_INITIALIZER)            ? sizeof(ast_dss_initializer_t) :
            (type == AST_DSS_INITIALIZER_ITEM)       ? sizeof(ast_dss_initializer_item_t) :
            (type == AST_ELSE_CLAUSE)                ? sizeof(ast_else_clause_t) :
            (type == AST_EXIT_STATEMENT)             ? sizeof(ast_exit_statement_t) :
            (type == AST_EXPRESSION)                 ? sizeof(ast_expression_t) :
            (type == AST_EXPRESSION_LIST)            ? sizeof(ast_expression_list_t) :
            (type == AST_FINAL_ELSE_CLAUSE)          ? sizeof(ast_final_else_clause_t) :
            (type == AST_FOR_CLAUSE)                 ? sizeof(ast_for_clause_t) :
            (type == AST_FORMATTED_STRING)           ? sizeof(ast_formatted_string_t) :
            (type == AST_FUNCTION_BODY)              ? sizeof(ast_function_body_t) :
            (type == AST_FUNCTION_BODY_ELEMENT)      ? sizeof(ast_function_body_element_t) :
            (type == AST_FUNCTION_BODY_LIST)         ? sizeof(ast_function_body_list_t) :
            (type == AST_FUNCTION_BODY_PRELIST)      ? sizeof(ast_function_body_prelist_t) :
            (type == AST_FUNCTION_DEFINITION)        ? sizeof(ast_function_definition_t) :
            (type == AST_FUNCTION_NAME)              ? sizeof(ast_function_name_t) :
            (type == AST_FUNCTION_PARAMETERS)        ? sizeof(ast_function_parameters_t) :
            (type == AST_FUNCTION_REFERENCE)         ? sizeof(ast_function_reference_t) :
            (type == AST_IF_CLAUSE)                  ? sizeof(ast_if_clause_t) :
            (type == AST_IMPORT_STATEMENT)           ? sizeof(ast_import_statement_t) :
            (type == AST_INITIALIZER)                ? sizeof(ast_initializer_t) :
            (type == AST_LIST_INIT)                  ? sizeof(ast_list_init_t) :
            (type == AST_LIST_REFERENCE)             ? sizeof(ast_list_reference_t) :
            (type == AST_LITERAL_TYPE_NAME)          ? sizeof(ast_literal_type_name_t) :
            (type == AST_LOOP_BODY)                  ? sizeof(ast_loop_body_t) :
            (type == AST_LOOP_BODY_ELEMENT)          ? sizeof(ast_loop_body_element_t) :
            (type == AST_LOOP_BODY_LIST)             ? sizeof(ast_loop_body_list_t) :
            (type == AST_LOOP_BODY_PRELIST)          ? sizeof(ast_loop_body_prelist_t) :
            (type == AST_PRIMARY_EXPRESSION)         ? sizeof(ast_primary_expression_t) :
            (type == AST_RETURN_STATEMENT)           ? sizeof(ast_return_statement_t) :
            (type == AST_START_BLOCK)                ? sizeof(ast_start_block_t) :
            (type == AST_STRUCT_DEFINITION)          ? sizeof(ast_struct_definition_t) :
            (type == AST_STRUCT_INIT)                ? sizeof(ast_struct_init_t) :
            (type == AST_TRANSLATION_UNIT)           ? sizeof(ast_translation_unit_t) :
            (type == AST_TRANSLATION_UNIT_ELEMENT)   ? sizeof(ast_translation_unit_element_t) :
            (type == AST_TYPE_NAME)                  ? sizeof(ast_type_name_t) :
            (type == AST_WHILE_CLAUSE)               ? sizeof(ast_while_clause_t) :
                                                       (size_t)-1;
}
