/**
 * @file ./out/ast/bool_literal.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the bool_literal data structure.
 *
 * bool_literal (
 *     TOK_TRUE |
 *     TOK_FALSE
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     terminal rule element: TOK_TRUE
 *     terminal rule element: TOK_FALSE
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_bool_literal(ast_bool_literal_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
