/**
 * @file ./out/ast/compound_reference_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the compound_reference_element data structure.
 *
 * compound_reference_element (
 *     TOK_IDENTIFIER |
 *     function_reference |
 *     list_reference
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       terminal rule element: TOK_IDENTIFIER
 *       non-terminal rule element: function_reference
 *     end or_function (1200)
 *     non-terminal rule element: list_reference
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_compound_reference_element(ast_compound_reference_element_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    if(node->function_reference != NULL)
        TRAVERSE_NODE(function_reference);
    else if(node->list_reference != NULL)
        TRAVERSE_NODE(list_reference);
    else if(node->IDENTIFIER != NULL)
        TRAVERSE_TOKEN(node->IDENTIFIER);


    RETURN();
}
