/**
 * @file ./out/ast/compound_reference.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the compound_reference data structure.
 *
 * compound_reference (
 *     compound_reference_element ( TOK_DOT compound_reference_element ) *
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: compound_reference_element
 *   begin zero_or_more_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_DOT
 *       non-terminal rule element: compound_reference_element
 *     end grouping_function (1200)
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_compound_reference(ast_compound_reference_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_LIST(compound_reference_element);

    RETURN();
}
