/**
 * @file ./out/ast/compound_name.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the compound_name data structure.
 *
 * compound_name (
 *     TOK_IDENTIFIER ( TOK_DOT TOK_IDENTIFIER ) *
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_IDENTIFIER
 *   begin zero_or_more_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_DOT
 *       terminal rule element: TOK_IDENTIFIER
 *     end grouping_function (1200)
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_compound_name(ast_compound_name_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
