/**
 * @file ./out/ast/data_declaration.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the data_declaration data structure.
 *
 * data_declaration (
 *     type_name TOK_IDENTIFIER
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: type_name
 *   terminal rule element: TOK_IDENTIFIER
 * end grouping_function (1000)
 *
 */
void traverse_data_declaration(ast_data_declaration_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
