/**
 * @file ./out/ast/dict_init.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the dict_init data structure.
 *
 * dict_init (
 *     TOK_OSBRACE dss_initializer TOK_CSBRACE
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_OSBRACE
 *   non-terminal rule element: dss_initializer
 *   terminal rule element: TOK_CSBRACE
 * end grouping_function (1000)
 *
 */
void traverse_dict_init(ast_dict_init_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_NODE(dss_initializer);

    RETURN();
}
