/**
 * @file ./out/ast/dss_initializer.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the dss_initializer data structure.
 *
 * dss_initializer (
 *     dss_initializer_item ( TOK_COMMA dss_initializer_item ) *
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: dss_initializer_item
 *   begin zero_or_more_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_COMMA
 *       non-terminal rule element: dss_initializer_item
 *     end grouping_function (1200)
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_dss_initializer(ast_dss_initializer_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
