/**
 * @file ./out/ast/else_clause.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the else_clause data structure.
 *
 * else_clause (
 *     TOK_ELSE TOK_OPAREN expression TOK_CPAREN function_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_ELSE
 *   terminal rule element: TOK_OPAREN
 *   non-terminal rule element: expression
 *   terminal rule element: TOK_CPAREN
 *   non-terminal rule element: function_body
 * end grouping_function (1000)
 *
 */
void traverse_else_clause(ast_else_clause_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_NODE(expression);
    TRAVERSE_NODE(function_body);

    RETURN();
}
