/**
 * @file ./out/ast/exit_statement.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the exit_statement data structure.
 *
 * exit_statement (
 *     TOK_EXIT TOK_OPAREN expression TOK_CPAREN
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_EXIT
 *   terminal rule element: TOK_OPAREN
 *   non-terminal rule element: expression
 *   terminal rule element: TOK_CPAREN
 * end grouping_function (1000)
 *
 */
void traverse_exit_statement(ast_exit_statement_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
