/**
 * @file ./out/ast/expression.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the expression data structure.
 *
 * expression (
 *     expression TOK_STAR expression |
 *     expression TOK_SLASH expression |
 *     expression TOK_PERCENT expression |
 *     expression TOK_PLUS expression |
 *     expression TOK_MINUS expression |
 *     expression ( TOK_CPBRACE | TOK_GT ) expression |
 *     expression ( TOK_OPBRACE | TOK_LT ) expression |
 *     expression ( TOK_CPBRACE_EQUAL | TOK_GTE ) expression |
 *     expression ( TOK_OPBRACE_EQUAL | TOK_LTE ) expression |
 *     expression ( TOK_EQUAL_EQUAL | TOK_EQU ) expression |
 *     expression ( TOK_BANG_EQUAL | TOK_NEQU ) expression |
 *     expression ( TOK_AMP | TOK_AND ) expression |
 *     expression ( TOK_BAR | TOK_OR ) expression |
 *     expression TOK_CARET expression |
 *     ( TOK_BANG | TOK_NOT ) expression |
 *     TOK_MINUS expression |
 *     primary_expression
 * )
 *
 * Expressions are parsed using Dijkstra's shunting yard algorithm and
 * so are given by a list of primary_expressions in postfix format.
 *
 */
void traverse_expression(ast_expression_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_LIST(primary_expression);

    RETURN();
}
