/**
 * @file ./out/ast/for_clause.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the for_clause data structure.
 *
 * for_clause (
 *     TOK_FOR ( TOK_OPAREN ( literal_type_name ? TOK_IDENTIFIER TOK_IN ) ? expression TOK_CPAREN ) ? loop_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_FOR
 *   begin zero_or_one_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_OPAREN
 *       begin zero_or_one_function (1300)
 *         begin grouping_function (1400)
 *           begin zero_or_one_function (1500)
 *             non-terminal rule element: literal_type_name
 *           end zero_or_one_function (1500)
 *           terminal rule element: TOK_IDENTIFIER
 *           terminal rule element: TOK_IN
 *         end grouping_function (1400)
 *       end zero_or_one_function (1300)
 *       non-terminal rule element: expression
 *       terminal rule element: TOK_CPAREN
 *     end grouping_function (1200)
 *   end zero_or_one_function (1100)
 *   non-terminal rule element: loop_body
 * end grouping_function (1000)
 *
 */
void traverse_for_clause(ast_for_clause_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_NODE(literal_type_name);
    TRAVERSE_TOKEN(node->IDENTIFIER);
    TRAVERSE_NODE(expression);
    TRAVERSE_NODE(loop_body);

    RETURN();
}
