/**
 * @file ./out/ast/function_reference.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_reference data structure.
 *
 * function_reference (
 *     TOK_IDENTIFIER TOK_OPAREN expression_list TOK_CPAREN
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_IDENTIFIER
 *   terminal rule element: TOK_OPAREN
 *   non-terminal rule element: expression_list
 *   terminal rule element: TOK_CPAREN
 * end grouping_function (1000)
 *
 */
void traverse_function_reference(ast_function_reference_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
