/**
 * @file ./out/ast/function_body_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_body_element data structure.
 *
 * function_body_element (
 *     assignment |
 *     compound_reference |
 *     data_definition |
 *     struct_definition |
 *     if_clause |
 *     while_clause |
 *     do_clause |
 *     for_clause |
 *     return_statement |
 *     exit_statement |
 *     TOK_INLINE
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         begin or_function (1400)
 *           begin or_function (1500)
 *             begin or_function (1600)
 *               begin or_function (1700)
 *                 begin or_function (1800)
 *                   begin or_function (1900)
 *                     begin or_function (2000)
 *                       non-terminal rule element: assignment
 *                       non-terminal rule element: compound_reference
 *                     end or_function (2000)
 *                     non-terminal rule element: data_definition
 *                   end or_function (1900)
 *                   non-terminal rule element: struct_definition
 *                 end or_function (1800)
 *                 non-terminal rule element: if_clause
 *               end or_function (1700)
 *               non-terminal rule element: while_clause
 *             end or_function (1600)
 *             non-terminal rule element: do_clause
 *           end or_function (1500)
 *           non-terminal rule element: for_clause
 *         end or_function (1400)
 *         non-terminal rule element: return_statement
 *       end or_function (1300)
 *       non-terminal rule element: exit_statement
 *     end or_function (1200)
 *     terminal rule element: TOK_INLINE
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_function_body_element(ast_function_body_element_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
