/**
 * @file ./out/ast/function_body.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_body data structure.
 *
 * function_body (
 *     TOK_OCBRACE function_body_list TOK_CCBRACE
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_OCBRACE
 *   non-terminal rule element: function_body_list
 *   terminal rule element: TOK_CCBRACE
 * end grouping_function (1000)
 *
 */
void traverse_function_body(ast_function_body_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_NODE(function_body_list);

    RETURN();
}
