/**
 * @file ./out/ast/function_definition.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_definition data structure.
 *
 * function_definition (
 *     function_name function_parameters function_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: function_name
 *   non-terminal rule element: function_parameters
 *   non-terminal rule element: function_body
 * end grouping_function (1000)
 *
 */
void traverse_function_definition(ast_function_definition_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_NODE(function_name);
    TRAVERSE_NODE(function_parameters);
    TRAVERSE_NODE(function_body);

    RETURN();
}
