/**
 * @file ./out/ast/function_body_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_body_element data structure.
 *
 * function_body_element (
 *     assignment |
 *     compound_reference |
 *     data_definition |
 *     struct_definition |
 *     if_clause |
 *     while_clause |
 *     do_clause |
 *     for_clause |
 *     return_statement |
 *     exit_statement |
 *     TOK_INLINE
 * )
 *
 */
void traverse_function_body_element(ast_function_body_element_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    if(node->INLINE != NULL)
        PRINT("token: INLINE {}\n");
    else {
        switch(node->nterm->type) {
            case AST_ASSIGNMENT:
                TRAVERSE_NTERM(assignment);
                break;
            case AST_COMPOUND_REFERENCE:
                TRAVERSE_NTERM(compound_reference);
                break;
            case AST_DATA_DEFINITION:
                TRAVERSE_NTERM(data_definition);
                break;
            case AST_STRUCT_DEFINITION:
                TRAVERSE_NTERM(struct_definition);
                break;
            case AST_IF_CLAUSE:
                TRAVERSE_NTERM(if_clause);
                break;
            case AST_WHILE_CLAUSE:
                TRAVERSE_NTERM(while_clause);
                break;
            case AST_DO_CLAUSE:
                TRAVERSE_NTERM(do_clause);
                break;
            case AST_FOR_CLAUSE:
                TRAVERSE_NTERM(for_clause);
                break;
            case AST_RETURN_STATEMENT:
                TRAVERSE_NTERM(return_statement);
                break;
            case AST_EXIT_STATEMENT:
                TRAVERSE_NTERM(exit_statement);
                break;
            default:
                FATAL("internal AST error: Unknown body element type: %d", node->nterm->type);
        }
    }

    RETURN();
}
