/**
 * @file ./out/ast/function_body_list.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_body_list data structure.
 *
 * function_body_list (
 *     function_body_prelist function_body_prelist *
 * )
 *
 *
 * begin grouping_function (1000)
 *   non-terminal rule element: function_body_prelist
 *   begin zero_or_more_function (1100)
 *     non-terminal rule element: function_body_prelist
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_function_body_list(ast_function_body_list_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
