/**
 * @file ./out/ast/function_body_prelist.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_body_prelist data structure.
 *
 * function_body_prelist (
 *     function_body_element |
 *     function_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     non-terminal rule element: function_body_element
 *     non-terminal rule element: function_body
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_function_body_prelist(ast_function_body_prelist_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    switch(node->nterm->type) {
        case AST_FUNCTION_BODY_ELEMENT:
            TRAVERSE_NTERM(function_body_element);
            break;
        case AST_FUNCTION_BODY:
            TRAVERSE_NTERM(function_body);
            break;
        default:
            FATAL("internal AST error: Unknown body element type: %d", node->nterm->type);
    }

    RETURN();
}
