/**
 * @file ./out/ast/function_parameters.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_parameters data structure.
 *
 * function_parameters (
 *     TOK_OPAREN ( data_declaration ( TOK_COMMA data_declaration ) * ) ? TOK_CPAREN
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_OPAREN
 *   begin zero_or_one_function (1100)
 *     begin grouping_function (1200)
 *       non-terminal rule element: data_declaration
 *       begin zero_or_more_function (1300)
 *         begin grouping_function (1400)
 *           terminal rule element: TOK_COMMA
 *           non-terminal rule element: data_declaration
 *         end grouping_function (1400)
 *       end zero_or_more_function (1300)
 *     end grouping_function (1200)
 *   end zero_or_one_function (1100)
 *   terminal rule element: TOK_CPAREN
 * end grouping_function (1000)
 *
 */
void traverse_function_parameters(ast_function_parameters_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_LIST(data_declaration);

    RETURN();
}
