/**
 * @file ./out/ast/function_name.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the function_name data structure.
 *
 * function_name (
 *     ( type_name TOK_IDENTIFIER ) |
 *     ( TOK_NOTHING TOK_IDENTIFIER )
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin grouping_function (1200)
 *       non-terminal rule element: type_name
 *       terminal rule element: TOK_IDENTIFIER
 *     end grouping_function (1200)
 *     begin grouping_function (1300)
 *       terminal rule element: TOK_NOTHING
 *       terminal rule element: TOK_IDENTIFIER
 *     end grouping_function (1300)
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_function_name(ast_function_name_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
