/**
 * @file ./out/ast/if_clause.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the if_clause data structure.
 *
 * if_clause (
 *     TOK_IF TOK_OPAREN expression TOK_CPAREN function_body else_clause * final_else_clause ?
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_IF
 *   terminal rule element: TOK_OPAREN
 *   non-terminal rule element: expression
 *   terminal rule element: TOK_CPAREN
 *   non-terminal rule element: function_body
 *   begin zero_or_more_function (1100)
 *     non-terminal rule element: else_clause
 *   end zero_or_more_function (1100)
 *   begin zero_or_one_function (1200)
 *     non-terminal rule element: final_else_clause
 *   end zero_or_one_function (1200)
 * end grouping_function (1000)
 *
 */
void traverse_if_clause(ast_if_clause_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
