/**
 * @file ./out/ast/import_statement.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the import_statement data structure.
 *
 * import_statement (
 *     TOK_IMPORT TOK_STRING_LITERAL
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_IMPORT
 *   terminal rule element: TOK_STRING_LITERAL
 * end grouping_function (1000)
 *
 */
void traverse_import_statement(ast_import_statement_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
