/**
 * @file ./out/ast/initializer.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the initializer data structure.
 *
 * initializer (
 *     expression |
 *     list_init |
 *     dict_init |
 *     struct_init
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         non-terminal rule element: expression
 *         non-terminal rule element: list_init
 *       end or_function (1300)
 *       non-terminal rule element: dict_init
 *     end or_function (1200)
 *     non-terminal rule element: struct_init
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_initializer(ast_initializer_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
