/**
 * @file ./out/ast/list_reference.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the list_reference data structure.
 *
 * list_reference (
 *     TOK_IDENTIFIER TOK_OSBRACE expression TOK_CSBRACE ( TOK_OSBRACE expression TOK_CSBRACE ) *
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_IDENTIFIER
 *   terminal rule element: TOK_OSBRACE
 *   non-terminal rule element: expression
 *   terminal rule element: TOK_CSBRACE
 *   begin zero_or_more_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_OSBRACE
 *       non-terminal rule element: expression
 *       terminal rule element: TOK_CSBRACE
 *     end grouping_function (1200)
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_list_reference(ast_list_reference_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_TOKEN(node->IDENTIFIER);
    TRAVERSE_LIST(expression);

    RETURN();
}
