/**
 * @file ./out/ast/literal_type_name.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the literal_type_name data structure.
 *
 * literal_type_name (
 *     TOK_INT |
 *     TOK_FLOAT |
 *     TOK_STRING |
 *     TOK_LIST |
 *     TOK_DICT |
 *     TOK_BOOL
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         begin or_function (1400)
 *           begin or_function (1500)
 *             terminal rule element: TOK_INT
 *             terminal rule element: TOK_FLOAT
 *           end or_function (1500)
 *           terminal rule element: TOK_STRING
 *         end or_function (1400)
 *         terminal rule element: TOK_LIST
 *       end or_function (1300)
 *       terminal rule element: TOK_DICT
 *     end or_function (1200)
 *     terminal rule element: TOK_BOOL
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_literal_type_name(ast_literal_type_name_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_TOKEN(node->tok);

    RETURN();
}
