/**
 * @file ./out/ast/loop_body_prelist.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the loop_body_prelist data structure.
 *
 * loop_body_prelist (
 *     loop_body_element |
 *     loop_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     non-terminal rule element: loop_body_element
 *     non-terminal rule element: loop_body
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_loop_body_prelist(ast_loop_body_prelist_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
