/**
 * @file ./out/ast/loop_body_element.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the loop_body_element data structure.
 *
 * loop_body_element (
 *     function_body_element |
 *     TOK_CONTINUE |
 *     TOK_BREAK
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       non-terminal rule element: function_body_element
 *       terminal rule element: TOK_CONTINUE
 *     end or_function (1200)
 *     terminal rule element: TOK_BREAK
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_loop_body_element(ast_loop_body_element_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    if(node->tok != NULL)
        TRAVERSE_TOKEN(node->tok);
    else
        TRAVERSE_NODE(function_body_element);

    RETURN();
}
