/**
 * @file ./out/ast/primary_expression.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the primary_expression data structure.
 *
 * primary_expression (
 *     TOK_INT_LITERAL |
 *     TOK_FLOAT_LITERAL |
 *     formatted_string |
 *     bool_literal |
 *     ( TOK_OPAREN expression TOK_CPAREN ) |
 *     compound_reference
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     begin or_function (1200)
 *       begin or_function (1300)
 *         begin or_function (1400)
 *           begin or_function (1500)
 *             terminal rule element: TOK_INT_LITERAL
 *             terminal rule element: TOK_FLOAT_LITERAL
 *           end or_function (1500)
 *           non-terminal rule element: formatted_string
 *         end or_function (1400)
 *         non-terminal rule element: bool_literal
 *       end or_function (1300)
 *       begin grouping_function (1600)
 *         terminal rule element: TOK_OPAREN
 *         non-terminal rule element: expression
 *         terminal rule element: TOK_CPAREN
 *       end grouping_function (1600)
 *     end or_function (1200)
 *     non-terminal rule element: compound_reference
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_primary_expression(ast_primary_expression_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    if(node->token != NULL)
        TRAVERSE_TOKEN(node->token);
    else {
        switch(node->nterm->type) {
            case AST_FORMATTED_STRING:
                TRAVERSE_NTERM(formatted_string);
                break;
            case AST_BOOL_LITERAL:
                TRAVERSE_NTERM(bool_literal);
                break;
            case AST_EXPRESSION:
                TRAVERSE_NTERM(expression);
                break;
            case AST_COMPOUND_REFERENCE:
                TRAVERSE_NTERM(compound_reference);
                break;
            default:
                FATAL("internal AST error: Unknown primary expression type: %d", node->nterm->type);
        }
    }

    RETURN();
}
