/**
 * @file ./out/ast/return_statement.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the return_statement data structure.
 *
 * return_statement (
 *     TOK_RETURN ( TOK_OPAREN expression ? TOK_CPAREN ) ?
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_RETURN
 *   begin zero_or_one_function (1100)
 *     begin grouping_function (1200)
 *       terminal rule element: TOK_OPAREN
 *       begin zero_or_one_function (1300)
 *         non-terminal rule element: expression
 *       end zero_or_one_function (1300)
 *       terminal rule element: TOK_CPAREN
 *     end grouping_function (1200)
 *   end zero_or_one_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_return_statement(ast_return_statement_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
