/**
 * @file ./out/ast/start_block.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the start_block data structure.
 *
 * start_block (
 *     TOK_START function_body
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_START
 *   non-terminal rule element: function_body
 * end grouping_function (1000)
 *
 */
void traverse_start_block(ast_start_block_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    // ast implementation is TBD


    RETURN();
}
