/**
 * @file ./out/ast/struct_definition.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the struct_definition data structure.
 *
 * struct_definition (
 *     TOK_STRUCT TOK_IDENTIFIER TOK_OCBRACE data_declaration ( data_declaration ) * TOK_CCBRACE
 * )
 *
 *
 * begin grouping_function (1000)
 *   terminal rule element: TOK_STRUCT
 *   terminal rule element: TOK_IDENTIFIER
 *   terminal rule element: TOK_OCBRACE
 *   non-terminal rule element: data_declaration
 *   begin zero_or_more_function (1100)
 *     begin grouping_function (1200)
 *       non-terminal rule element: data_declaration
 *     end grouping_function (1200)
 *   end zero_or_more_function (1100)
 *   terminal rule element: TOK_CCBRACE
 * end grouping_function (1000)
 *
 */
void traverse_struct_definition(ast_struct_definition_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_TOKEN(node->IDENTIFIER);
    TRAVERSE_LIST(data_declaration);

    RETURN();
}
