/**
 * @file ./out/ast/translation_unit.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the translation_unit data structure.
 *
 * translation_unit (
 *     translation_unit_element *
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin zero_or_more_function (1100)
 *     non-terminal rule element: translation_unit_element
 *   end zero_or_more_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_translation_unit(ast_translation_unit_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    TRAVERSE_LIST(translation_unit_element);

    RETURN();
}
