/**
 * @file ./out/ast/type_name.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>

#include "trace.h"
#include "ast_protos.h"

/*
 * Traverse the type_name data structure.
 *
 * type_name (
 *     literal_type_name |
 *     compound_name
 * )
 *
 *
 * begin grouping_function (1000)
 *   begin or_function (1100)
 *     non-terminal rule element: literal_type_name
 *     non-terminal rule element: compound_name
 *   end or_function (1100)
 * end grouping_function (1000)
 *
 */
void traverse_type_name(ast_type_name_t* node) {

    ENTER;
    if(node == NULL)
        RETURN();

    switch(node->nterm->type) {
        case AST_LITERAL_TYPE_NAME:
            TRAVERSE_NTERM(literal_type_name);
            break;
        case AST_COMPOUND_NAME:
            TRAVERSE_NTERM(compound_name);
            break;
        default:
            FATAL("internal AST error: Unknown type_name type: %d", node->nterm->type);
    }

    RETURN();
}
